// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADiuaXt4BFgGGGU2v8GVXPoCJUXGqJbMg',
    appId: '1:216316758655:web:7c2167d8c36be0346e8d4a',
    messagingSenderId: '216316758655',
    projectId: 'talipafast-proto',
    authDomain: 'talipafast-proto.firebaseapp.com',
    storageBucket: 'talipafast-proto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVy0cCrJ5YoEbBAeH6WL2dIssXIxcXBO4',
    appId: '1:216316758655:android:39fcbf9ef61fc83d6e8d4a',
    messagingSenderId: '216316758655',
    projectId: 'talipafast-proto',
    storageBucket: 'talipafast-proto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeXfaheqDxQN5miZ5h3YwbtAh5QmXyc2Y',
    appId: '1:216316758655:ios:540d516421f3e58a6e8d4a',
    messagingSenderId: '216316758655',
    projectId: 'talipafast-proto',
    storageBucket: 'talipafast-proto.appspot.com',
    iosBundleId: 'com.example.talipafast',
  );
}
